[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'expected'
version = '2025.0.1'
dependencies = [
  'flask',
  'gunicorn',
  'Flask-WTF', 
  'matplotlib', 
  'pandas', 
  'google-auth',
  'gspread',
  'pydantic'
]

[project.optional-dependencies]
test = ['pytest', 'pytest-cov']
dev = ['flake8', 'mypy']
# zsh: pip install -e '.[test]'


[tool.setuptools.package-dir]
expected = 'expected'

# ModuleNotFoundError: No module named 'flask_wtf'
# インストール後、flask run で外部ライブラリが読み込めない場合は、仮想環境を入り直す。